
all:
	g++ -Wall -g -std=c++17 RedBlackTree.cpp RedBlackTreeTestsFirstStep.cpp -o rbtfirst-tests
	g++ -Wall -g -std=c++17 RedBlackTree.cpp RedBlackTreeTests.cpp -o rbt-tests
	
runfirst:
	./rbtfirst-tests


tryfirst: all runfirst

run:
	./rbt-tests

try: all run


